### ISSUE TITLE
Implement the PWM Out to Set the Motor Speeds

### ISSUE THREAD

**Issue by lymacasm** [uvic-auvic/Motor_Controller_2.0#17]
Should configure 8 PWM outputs (one for each motor) using timers capture/compare functionality. Functionality should be added to set the PWM of each timer using a function, whose name etc will be provided.

**Comment by batesandy123** [comment]
All the PWM channels might not be able on your breakout board. Make sure to leave a space for ones that are not implemented so it's obvious we have to complete them later.

**Comment by batesandy123** [comment]
Merged and confirmed as of 2018-05-07
