### ISSUE TITLE
Add a command to set all the motor at the same time

### ISSUE THREAD

**Issue by batesandy123** [uvic-auvic/Motor_Controller_2.0#2]
Example:

Motor Set Speed allows us to set all of the motor speeds in one command. Not sure how will do it yet but will work out a system for this and document in this projects wiki.

MSS dd dd dd dd dd dd dd dd \r\n

**Comment by poornack** [comment]
I am going to put this task aside for now. I will be working on the PWM in task(issue #4 ) first. Someone else  looking for a firmware task in the meantime can pick this up.

**Comment by poornack** [comment]
Code merged to master. Refer to PR #20 for more information.
