### ISSUE TITLE
Implement a system to reset RPM to zero if no edge is detected in a while

### ISSUE THREAD

**Issue by batesandy123** [uvic-auvic/Motor_Controller_2.0#27]
One of the current problems is that RPM will stay at whatever value is last read. For example if the last read RPM is 7000 and the motor_controller does not see any more edges then the RPM will stay at 7000. 

Our system should set RPM to 0 if it does not see any edges in a certain amount of time.

**Comment by batesandy123** [comment]
After talking to Poorna we think the easiest way to do this is by monitoring the current out of the motor controller. If it is below 20mA above just the ESC draw then we will set RPM to off. Waiting for issue #12

**Comment by lymacasm** [comment]
Good idea!

**Comment by lymacasm** [comment]
Instead of doing this, both the index of the last data transfer, and the contents of the data transfer are investigated. If they have not changed, then the RPM for that motor should be set to 0. See pull request #37 .
