### ISSUE TITLE
Implement PWM In to read the Motor RPM

### ISSUE THREAD

**Issue by batesandy123** [uvic-auvic/Motor_Controller_2.0#4]
Implement a way to monitor the RPM. This should be done use timers with DMA configured as the input. Store multiple time stamps from a timer and then do math to figure out the period. Inversing the period will give the frequency which can be multiplied by 60 for RPM. You can view the schematics in the repo to see which motors are connected to what pins.

**Comment by lymacasm** [comment]
Do you think we could split this issue into two? We could have different files, one for PWN_in, and one for PWM_out. That would keep them independent, and I feel like the two tasks here are quite large on their own.

**Comment by lymacasm** [comment]
I've made this the PWM in issue, and I will be making a PWM out issue shortly.

**Comment by poornack** [comment]
Code for this issue has been completed and is ready for review. Pull request #19 has been created. Details about the code can be read in the pull request. Assigning this to Lyden review and merge to master.

**Comment by poornack** [comment]
Code merged to master. Refer to PR #19 for more information
